try {
    let a=10;
    console.log(`the value of a is ${a}`);
    console.log(b);

    
} catch (error) {
    console.log(error)
}